### ISSUE TITLE
Wrong link posted after builds succeed

### ISSUE THREAD

**Issue by alexandershestakov** [wooga/atlas-appcenter#4]
## Description

It looks like either something is wrong with this hockey plugin, or the way HockeyApp reports the link or the way we pass it on to the other parts of pipeline. 

## Steps to reproduce

Here's an example of mismatch, build report is showing a link for some build from half a year ago: https://wooga.slack.com/archives/C9R72UHKQ/p1555575033005900

I've checked several links and they had the same problem.

**Comment by Larusso** [comment]
Its save to say that we can close this now
